server:
  port: 18899
logging:
  level:
    com.yukikaze: info
    org.springframework: warn

##es搜索引擎url地址以及端口号,同环境就http://localhost:9200
esHttp: "http://124.223.0.216:9200"
##es搜索引擎指定的索引库,变更库名需要重新配置
#/termTags与/matchTags的索引库
esIndex: es_translation_index
#/listTags的索引库
listEsIndex: list_es_translation_index